<?
$page = "calls";
include "include.php"; 
echo "<div class=\"main_each\">\n";
echo "<table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" width=\"700\" class=\"content\">\n";
echo "<tr><td class=\"contenthead\">Setting Up Call Parameters.</td></tr>\n";
$SQL = "DELETE FROM call_priority";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "ALTER TABLE call_priority AUTO_INCREMENT=1";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_priority (call_priority_name, call_priority_colour, call_priority) VALUES ('Critical','red','1')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_priority (call_priority_name, call_priority_colour, call_priority) VALUES ('High','orange','2')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_priority (call_priority_name, call_priority_colour, call_priority) VALUES ('Medium','blue','3')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_priority (call_priority_name, call_priority_colour, call_priority) VALUES ('Low','grey','4')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_priority (call_priority_name, call_priority_colour, call_priority) VALUES ('Not Prioritised','white','5')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "DELETE FROM call_status";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "ALTER TABLE call_status AUTO_INCREMENT=1";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_status (call_status_name, call_status_colour) VALUES ('New','red')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_status (call_status_name, call_status_colour) VALUES ('Assigned','blue')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_status (call_status_name, call_status_colour) VALUES ('Awaiting More Info','orange')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT INTO call_status (call_status_name, call_status_colour) VALUES ('Closed','green')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "INSERT IGNORE config (config_name) VALUES ('calls')";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
$SQL = "UPDATE config SET config_value = 'set' WHERE config_name = 'calls'";
$result = mysql_query($SQL, $db) or die("Query failed." . $SQL);
echo "<tr><td>" . $SQL . "</td></tr>\n";
echo "</table>";
echo "</div>";
